# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Medium Unlimited
email: p.manoj.vivek@gmail.com
description: Read medium.com premium articles without subscription!
baseurl: "/medium-unlimited" # the subpath of your site, e.g. /blog
url: "hhttps://manojvivek.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username: manojVivek
paginate: 5
theme-dark: false #Set to true to change to dark website theme

plugins: [kramdown]
# Build settings
markdown: kramdown
